# Resolve fish from PATH because its absolute path differs by platform.
run-shell 'fish_path=$(command -v fish) && tmux set-option -g default-shell "$fish_path"'

# Sovle Esc delay
set -sg escape-time 0

# Set color
set -g default-terminal "tmux-256color"
set -g status-bg blue
set -as terminal-features ",xterm-256color:RGB"

# Enable mouse
set -g mouse on

# Set history-limit
set-option -g history-limit 10000

# Prevent copy from scrolling to bottom
unbind -T copy-mode-vi MouseDragEnd1Pane
