set -g cursor-style blinking-bar

# Sovle Esc delay
set -sg escape-time 0

# Set color
set -g default-terminal "tmux-256color"
set -g status-bg blue
set -as terminal-features ",xterm-256color:RGB"

# Enable mouse
set -g mouse on

# Set history-limit
set-option -g history-limit 10000

# Change prefix from C-b to C-Space
set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

