# Set default-shell
set-option -g default-shell /opt/homebrew/bin/fish

# Sovle Esc delay
set -sg escape-time 0

# Set color
set -g default-terminal "tmux-256color"
set -g status-bg blue
set -as terminal-features ",xterm-256color:RGB"

# Enable mouse
set -g mouse on

# Set history-limit
set-option -g history-limit 10000

# Set focus-events
set-option -g focus-events on

# Set extended-keys
set -g extended-keys
set -g extended-keys-format csi-u

# Change prefix from C-b to C-Space
set -g prefix C-Space
unbind-key C-b
bind-key C-Space send-prefix

# Prevent copy from scrolling to bottom
unbind -T copy-mode-vi MouseDragEnd1Pane

# List of plugins
# set -g @plugin 'tmux-plugins/tpm'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Dracula theme
# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline false
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, network, network-bandwidth, network-ping, attached-clients, network-vpn, weather, time
# set -g @dracula-plugins "time"
# set -g @dracula-foreground-colors "dark_gray"
# set -g @dracula-show-left-icon session

# Vim tmux navigator
# set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~/.tmux/plugins/tpm/tpm'

